Use with `vscode` and its `Data Wrangler`

In [1]:
import re
import numpy as np
import torch
import pickle

_GLOBAL = {}
def load_pt(file):
    data = torch.load(file)
    return data

def load_pkl(file):
    with open(file, 'rb') as f:
        data = pickle.load(f)
    return data

def load_np(file):
    return np.load(file, allow_pickle=True)
    
def load(file):
    if file.endswith('.pt'):
        data = load_pt(file)
    elif file.endswith('.pkl'):
        data = load_pkl(file)
    elif file.endswith('.npy') or file.endswith('.npz'):
        data = load_np(file)
    return data

def expand_dict(data,prefix=''):
    for k, v in data.items():
        # 如果k有非下划线符号，全部替换成_
        k = re.sub(r'[^a-zA-Z0-9_]', '_', k)
        print(f'{k}: {v}, {type(v)}')
        if isinstance(v, dict):
            expand_dict(v,f'{prefix}{k}一')
        else:
            if isinstance(v, torch.Tensor) and v.size(0) == 1:
                print(f'squeezed: {prefix}{k}')
                v = v.squeeze(0)
            elif isinstance(v, np.ndarray):
                ...
            _GLOBAL[f'{prefix}{k}'] = v

def get_global(data):
    expand_dict(data)
    globals().update(_GLOBAL)


In [2]:
_file = '/home/n/document/code/GVHMR/output/demo/jumper/preprocess/yolo_track.npz'
_file = '/home/n/document/code/GVHMR/output/demo/jumper/mocap_gvhmr_jumper.npz'
get_global(load(_file))

smplx_gvhmr_0_global_pose_: [[-0.20199461  0.01855306  0.07525941 ...  0.04557381  0.12640218
  -0.32964024]
 [-0.20809214  0.01819157  0.08074344 ...  0.05174107  0.12453608
  -0.31980428]
 [-0.23026986  0.01606733  0.08591762 ...  0.056307    0.12745896
  -0.31672302]
 ...
 [-0.731419   -0.07268099  0.12138427 ... -0.24106713  0.24173373
  -0.3584189 ]
 [-0.74227947 -0.06513292  0.11816891 ... -0.2302942   0.24389154
  -0.3697973 ]
 [-0.73571944 -0.05932653  0.1182457  ... -0.24888061  0.23652509
  -0.3828442 ]], <class 'numpy.ndarray'>
smplx_gvhmr_0_global_rotate_: [[-0.32672453  1.7640775   0.04765491]
 [-0.33101234  1.7505035   0.05162775]
 [-0.3324129   1.7400144   0.05111685]
 [-0.33733234  1.7254002   0.04745818]
 [-0.33819997  1.7116843   0.042553  ]
 [-0.3412784   1.6933953   0.03956825]
 [-0.33659172  1.6811672   0.03524914]
 [-0.33125788  1.6668748   0.04020363]
 [-0.32268143  1.6514856   0.03910866]
 [-0.31479123  1.6312432   0.03065857]
 [-0.31018722  1.6088687   0.035241